#!/bin/sh

num_lines='10'
from() { cat; }
to() { cat; }

[ "$1" != "-r" ] && exec rlwrap -a -s 0 -r -b "(){}[],+=^#;|&%" "$0" -r "$@"

while [ $# -gt 0 ] ; do
  case $1 in
    -r) shift;;
    -h) echo "usage: $0 [-n num_lines] [--] [dir]"; exit 1;;
    -n) shift; num_lines="$1"; shift;;
    -[0-9]*) num_lines=`echo $1 | sed 's/^-//'`; shift;;
    *) break;;
  esac
done

dir="${1:-.}"

[ -f "$dir/out" ] || { echo "$dir/out: does not exist"; exit 1; }
[ -p "$dir/in" ] || { echo "$dir/in: does not exist or not pipe"; exit 1; }
[ -f "$dir/../rc.conf" ] && . "$dir/../rc.conf"
[ -f "$dir/rc.conf" ] && . "$dir/rc.conf"

{
  tail -n $num_lines -f "$dir/out" | from \
  | awk -F '[ ]' -v 'clear=\033[0m' -v 'comment=\033[32m' '
      $3 == "-!-" {printf("%s%s%s\n", comment, $0, clear); next;}
      /^[0-9]+-[0-9]+-[0-9]+ [0-9]+:[0-9]+ </ {
        $1 = "";
        sub(/^[ \t]*/, "");
      }
      {print;}'
} &

pid=$!
trap "kill $pid" 0
stty -echonl -echo
trap "stty '`stty -g`'" exit
to > "$dir/in"
