#!/bin/sh

tmpdir="/tmp/ns.$USER"
timestamp="$tmpdir/im_timestamp"

dir=$HOME/talk

mkdir -p "$tmpdir"
[ -f "$timestamp" ] || touch "$timestamp"
touch "$timestamp.tmp"

show() {
  if [ "$1/out" -nt "$timestamp" ] ; then
    from() { cat; }
    [ -f "$1/../rc.conf" ] && . "$1/../rc.conf"
    [ -f "$1/rc.conf" ] && . "$1/rc.conf"
    echo "## $1"
    tail -3 "$1/out" | awk '$3 != "-!-" {print}' | from
    echo
  fi
}

for p in $dir/*/; do
  show "$p"
done
for p in $dir/*/*/; do
  show "$p"
done
mv "$timestamp.tmp" "$timestamp"
