#!/bin/sh

tmpdir="/tmp/ns.$USER"
timestamp="$tmpdir/im_timestamp"

dir=$HOME/talk

msg_head="\n## %s:\n"
msg_tail="---"

mkdir -p "$tmpdir"
[ -f "$timestamp" ] || touch "$timestamp"
touch "$timestamp.tmp"

show() {
  if [ "$1/out" -nt "$timestamp" ] ; then
    from() { cat; }
    [ -f "$1/../rc.conf" ] && . "$1/../rc.conf"
    [ -f "$1/rc.conf" ] && . "$1/rc.conf"
    printf "$msg_head" "$1"
    tail -5 "$1/out" | grep -v -e '-!-' | from
    printf '%s\n' "$msg_tail"
  fi
}

for p in $dir/*/; do
  show "$p"
done
for p in $dir/*/*/; do
  show "$p"
done
mv "$timestamp.tmp" "$timestamp"
