#!/bin/sh

num_lines='10'
use_color='yes'

unset codepage
for a; do
  case $a in
    -c) shift; codepage="$1"; shift ;;
    -h) echo "usage: $0 [-n num_lines] [-c encoding] [--] [dir]"; exit 1 ;;
    -n) shift; num_lines="$1"; shift ;;
    --) shift; break ;;
  esac
done

dir="${@:-.}"

[ -f "$dir/out" ] || { echo "$dir/out: does not exist"; exit 1; } 
[ -p "$dir/in" ] || { echo "$dir/in: does not exist or not pipe"; exit 1; } 
[ -f "$dir/../rc" ] && . "$dir/../rc"
[ -f "$dir/rc" ] && . "$dir/rc"

if [ -n "$codepage" ] ; then
  iconv_from="| while read s; do echo \"\$s\" | iconv -f $codepage; done"
  iconv_to="| while read s; do echo \"\$s\" | iconv -t $codepage; done"
fi

if [ _"$use_color" = _yes ] ; then
  black=`printf '\033[30m'`
  red=`printf '\033[31m'`
  green=`printf '\033[32m'`
  yellow=`printf '\033[33m'`
  blue=`printf '\033[34m'`
  magenta=`printf '\033[35m'`
  cyan=`printf '\033[36m'`
  white=`printf '\033[37m'`
  clear=`printf '\033[1m'`
fi

flt="s/^[-0-9]* \([^<]*\)<\([^>]*\)>/${blue}\1${white}<${green}\2${white}>/"

eval "tail -n $num_lines -f \"$dir/out\" $iconv_from" | sed -e "$flt" &
pid=$?
trap "kill $pid" 0
eval "cat $iconv_to" > "$dir/in"
