#!/bin/sh

action="show"
tmpdir="/tmp/ns.$USER"
timestamp="$tmpdir/im_timestamp"
tmp="$tmpdir/im_files"

for a; do
  case $a in
    -o) action='open'; shift;;
    -s) action='show'; shift;;
  esac
done

dir=${1:-$HOME/talk}

msg="\n## %s:\n"

mkdir -p "$tmpdir"
[ -f "$timestamp" ] || touch "$timestamp"

find "$dir" -mindepth 2 -newer "$timestamp" -name 'out' > "$tmp"
touch "$timestamp"

while read i; do
  # if file doesn't contain server stuff only
  if grep -v -q '\-!\-' $i  > /dev/null 2>&1 ; then
    case $action in
      open) im "`dirname "$i"`" ;;
      show)
        from() { cat; }
        [ -f "`dirname "$i"`/../rc.conf" ] && . "`dirname "$i"`/../rc.conf"
        [ -f "`dirname "$i"`/rc.conf" ] && . "`dirname "$i"`/rc.conf"
        printf "$msg" "$i"
        tail -5 $i | from | grep -v -e '-!-'
        ;;
    esac
    echo "---"
  fi
done < "$tmp"
